-- Idempotent CRM registration for the read-only loop monitoring projection.
begin;

insert into crm_objects (id,name,entity_table,description,default_view,display_field,immutable,hidden_in_sidebar,sort_order)
values ('reb_automation_loop_object','automation_loop','automation_loops','Durable automation loops and current operational health','table','Name',true,false,92),
       ('reb_automation_loop_run_object','automation_loop_run','automation_loop_runs','Invocation and run history for durable automation loops','table','Activity',true,false,93)
on conflict (id) do update set entity_table=excluded.entity_table, description=excluded.description, default_view=excluded.default_view, display_field=excluded.display_field, immutable=excluded.immutable, hidden_in_sidebar=excluded.hidden_in_sidebar, sort_order=excluded.sort_order, updated_at=now();

insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_name','reb_automation_loop_object','Name','text','name',true,null,null,null,0) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_workflow','reb_automation_loop_object','Workflow','text','workflow_name',false,null,null,null,1) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_lifecycle','reb_automation_loop_object','Lifecycle','enum','lifecycle',true,'["active","reference"]'::jsonb,null,null,2) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_operation','reb_automation_loop_object','Operation','enum','operation',true,'["scheduled","on-demand"]'::jsonb,null,null,3) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_status','reb_automation_loop_object','Current State','enum','current_status',false,'["running","waiting","succeeded","failed","exhausted","blocked","cancelled","skipped","never_run","unknown"]'::jsonb,null,null,4) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_attention','reb_automation_loop_object','Needs Attention','boolean','needs_attention',true,null,null,null,5) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_blocked','reb_automation_loop_object','Blocked','boolean','is_blocked',true,null,null,null,6) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_attention_reason','reb_automation_loop_object','Attention Reason','text','attention_reason',false,null,null,null,7) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_current_reason','reb_automation_loop_object','Current Reason','text','current_reason',false,null,null,null,8) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_last_activity','reb_automation_loop_object','Last Activity','date','last_activity_at',false,null,null,null,9) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_lease_expiry','reb_automation_loop_object','Lease Expires','date','lease_expires_at',false,null,null,null,10) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_lease_stale','reb_automation_loop_object','Lease Stale','boolean','lease_stale',true,null,null,null,11) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_approval','reb_automation_loop_object','Approval Required','boolean','approval_required',true,null,null,null,12) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_latest_scheduled','reb_automation_loop_object','Last Scheduled Receipt','date','latest_scheduled_at',false,null,null,null,13) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_scheduler','reb_automation_loop_object','Scheduler Health','text','scheduler_health',false,null,null,null,13) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_owner','reb_automation_loop_object','Owner App','text','owner_app',false,null,null,null,14) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_objective','reb_automation_loop_object','Objective','richtext','objective',false,null,null,null,15) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_error','reb_automation_loop_object','Observation Error','richtext','observation_error',false,null,null,null,16) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_observed','reb_automation_loop_object','Observed At','date','observed_at',true,null,null,null,17) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_activity','reb_automation_loop_run_object','Activity','text','activity_name',true,null,null,null,0) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_loop','reb_automation_loop_run_object','Loop','relation','loop_id',true,null,'reb_automation_loop_object','many_to_one',1) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_status','reb_automation_loop_run_object','Status','enum','status',true,'["running","waiting","succeeded","failed","exhausted","blocked","cancelled","skipped","unknown"]'::jsonb,null,null,2) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_origin','reb_automation_loop_run_object','Origin','enum','origin',false,'["scheduler","operator","parent","manual","legacy"]'::jsonb,null,null,3) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_reason','reb_automation_loop_run_object','Reason','text','reason',false,null,null,null,4) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_disposition','reb_automation_loop_run_object','Disposition','text','disposition',false,null,null,null,5) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_trigger','reb_automation_loop_run_object','Trigger Key Hash','text','trigger_key_hash',false,null,null,null,6) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_started','reb_automation_loop_run_object','Started At','date','started_at',false,null,null,null,7) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_finished','reb_automation_loop_run_object','Finished At','date','finished_at',false,null,null,null,8) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_duration','reb_automation_loop_run_object','Duration (ms)','number','duration_ms',false,null,null,null,9) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_approval','reb_automation_loop_run_object','Approval Required','boolean','approval_required',true,null,null,null,10) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_blocker','reb_automation_loop_run_object','Blocker','richtext','blocker',false,null,null,null,11) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_output','reb_automation_loop_run_object','Output Path','text','output_path',false,null,null,null,12) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_automation_loop_run_trace','reb_automation_loop_run_object','Trace ID','text','langfuse_trace_id',false,null,null,null,13) on conflict (id) do update set name=excluded.name,type=excluded.type,canonical_column=excluded.canonical_column,required=excluded.required,enum_values=excluded.enum_values,related_object_id=excluded.related_object_id,relationship_type=excluded.relationship_type,sort_order=excluded.sort_order,updated_at=now();

commit;
