-- PROTOTYPE ONLY: deterministic one-project/eight-task scratch fixture.
begin;

insert into crm_objects (id,name,entity_table,description,default_view,display_field,sort_order) values ('reb_project_object','project','projects','ReBattery Projects prototype','table','Name',90), ('reb_work_task_object','work_task','work_tasks','ReBattery Work Tasks prototype','kanban','Title',91) on conflict (id) do update set default_view=excluded.default_view, entity_table=excluded.entity_table;

insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_project_0','reb_project_object','Name','text','name',true,null , null, null,0) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_project_1','reb_project_object','Portfolio','text','portfolio',false,null , null, null,1) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_project_2','reb_project_object','Investment State','text','investment_state',false,null , null, null,2) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_project_3','reb_project_object','Outcome','richtext','outcome',false,null , null, null,3) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_project_4','reb_project_object','Principal Weakness','richtext','principal_weakness',false,null , null, null,4) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_project_5','reb_project_object','Reinvestment Direction','richtext','reinvestment_direction',false,null , null, null,5) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_project_6','reb_project_object','Last Reviewed','date','last_reviewed',false,null , null, null,6) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_0','reb_work_task_object','REB Key','text','reb_key',true,null , null, null,0) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_1','reb_work_task_object','Title','text','title',true,null , null, null,1) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_2','reb_work_task_object','Status','enum','status',false,'["Planned","Done","Retired"]'::jsonb , null, null,2) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_3','reb_work_task_object','Project','relation','project_id',false,null , 'reb_project_object', 'many_to_one',3) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_4','reb_work_task_object','Capability','text','capability',false,null , null, null,4) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_5','reb_work_task_object','Task Type','text','task_type',false,null , null, null,5) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_6','reb_work_task_object','Priority','text','priority',false,null , null, null,6) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_7','reb_work_task_object','Owner','text','owner',false,null , null, null,7) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_8','reb_work_task_object','Repository','text','repository',false,null , null, null,8) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_9','reb_work_task_object','Source Path','text','source_path',false,null , null, null,9) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_10','reb_work_task_object','External Linear ID','text','external_linear_id',false,null , null, null,10) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;
insert into crm_fields (id,object_id,name,type,canonical_column,required,enum_values,related_object_id,relationship_type,sort_order) values ('reb_work_task_11','reb_work_task_object','Current Impact','richtext','current_impact',false,null , null, null,11) on conflict (id) do update set canonical_column=excluded.canonical_column, related_object_id=excluded.related_object_id, relationship_type=excluded.relationship_type;

insert into projects (id,name,portfolio,investment_state,outcome,principal_weakness,reinvestment_direction,last_reviewed) values ('reb-project-supplier-inventory','Supplier inventory lifecycle','Marketplace supply and demand','implemented-unproven','Suppliers can safely intake, select, publish, synchronize, and withdraw inventory without corrupting listing or transaction state.','Review and promotion are not closed; Didier adoption is unfinished; batch maintenance no longer exists.','Close publish-to-review promotion; prove reconciliation invariants; decide whether to replace or retire batch editing.','2026-08-13') on conflict (id) do update set name=excluded.name, portfolio=excluded.portfolio, investment_state=excluded.investment_state, outcome=excluded.outcome, principal_weakness=excluded.principal_weakness, reinvestment_direction=excluded.reinvestment_direction, last_reviewed=excluded.last_reviewed;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-60','REB-60','Finalize the Supplier Listing API','Done','reb-project-supplier-inventory','Trusted intake and publication','implementation','P1','Ari','rebattery-platform','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-60.md','REB-60','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-61','REB-61','Connect a client AI agent to supplier listings from New Listing','Done','reb-project-supplier-inventory','Agent-assisted intake','implementation','P1','Ari','rebattery-platform','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-61.md','REB-61','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-62','REB-62','Prepare the Didier API and agent-skill handoff email','Planned','reb-project-supplier-inventory','Agent-assisted intake','implementation','P1','Hermes','rebattery-hermes','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-62.md','REB-62','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-64','REB-64','Synchronize imported eBay stock daily and remove unavailable listings','Done','reb-project-supplier-inventory','Channel stock alignment','implementation','P1','Ari','rebattery-platform','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-64.md','REB-64','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-65','REB-65','Verify the canonical listing workflow and show multi-unit conditions','Done','reb-project-supplier-inventory','Canonical selection and unit-condition workflow','implementation','P1','Ari','rebattery-platform','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-65.md','REB-65','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-66','REB-66','Bulk edit existing listings through a dedicated canonical workflow','Retired','reb-project-supplier-inventory','Existing-listing maintenance','implementation','P1','Ari','rebattery-platform','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-66.md','REB-66','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-68','REB-68','Use approved canonical data safely in new-listing search','Done','reb-project-supplier-inventory','Canonical selection and unit-condition workflow','implementation','P1','Ari','rebattery-platform','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-68.md','REB-68','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;
insert into work_tasks (id,reb_key,title,status,project_id,capability,task_type,priority,owner,repository,source_path,external_linear_id,current_impact) values ('reb-task-103','REB-103','Capture battery evidence for every successful listing API publish','Done','reb-project-supplier-inventory','Trusted intake and publication','implementation','P1','Ari','rebattery-platform','/root/.hermes/knowledgebase/90-archive/harness-retired-2026-08-05/work-tasks/tasks/REB-103.md','REB-103','Historical task imported for MVP UX proof.') on conflict (id) do update set status=excluded.status, title=excluded.title, project_id=excluded.project_id, source_path=excluded.source_path, external_linear_id=excluded.external_linear_id;

commit;
-- Verify exactly one project and eight tasks.
select name from projects where id = 'reb-project-supplier-inventory';
select reb_key,status,project_id from work_tasks where project_id = 'reb-project-supplier-inventory' order by reb_key;
